name: 🕸️ Build & Deploy Black Vertex Mirrors

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install --upgrade requests beautifulsoup4

    - name: Run Black Vertex script
      run: |
        python black_vertex.py
        echo "::group::Mirrored URLs"
        type mirrors\index.html
        echo "::endgroup::"

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add mirrors
        git commit -m "🔁 Update mirrors $(Get-Date -Format yyyy-MM-dd_HH-mm)" || echo "No changes to commit"

    - name: Push to gh-pages via subtree
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}
        git subtree push --prefix mirrors origin gh-pages
